package com.SHGroup.ParticlePlus;

public enum ParticleTypear {
	ARC,ATOM,BIG_BANG,BLEED,EARTH,DNA,EXPLODE,FLAME,FOUNTAIN,GRID,HELIX,JUMP,LINE,LOVE,MUSIC,SHIELD,SKYROCKET,SMOKE,STAR,TRACE,TURNPLAYER,VORTEX,WARP,WAVE,DEFAULT;
}
